"""Build manuscript Tables 7 and 8 from the validation summary CSV files."""
from pathlib import Path
import argparse
import csv
import json
import numpy as np

PACKAGE = Path(__file__).resolve().parents[1]
FIELDS7 = ["max_abs_displacement_error_nm", "rms_displacement_error_nm",
           "max_abs_velocity_error_nm_per_ps", "rms_velocity_error_nm_per_ps"]
FIELDS8 = ["max_eta", "terminal_eta", "max_eta_relative", "terminal_eta_relative"]


def read_rows(path):
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def write_rows(path, rows):
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def number(value):
    value = float(value)
    if value == 0:
        return "0"
    if 0.001 <= abs(value) < 1000:
        return format(value, ".3g")
    mantissa, exponent = format(value, ".2e").split("e")
    return mantissa + r"\times10^{" + str(int(exponent)) + "}"


def scientific(value):
    mantissa, exponent = format(float(value), ".2e").split("e")
    return mantissa + r"\times10^{" + str(int(exponent)) + "}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", type=Path, default=PACKAGE / "reproduced")
    args = parser.parse_args()
    result = args.results_dir
    errors = read_rows(result / "case3_error_decomposition_summary.csv")
    consistency = read_rows(result / "case3_carleman_consistency_summary.csv")
    assert len(errors) == 5 and len(consistency) == 5
    table7 = [{key: row[key] for key in ["comparison", "error_isolated"] + FIELDS7} for row in errors]
    # The fifth consistency record is a terminal-only VQLS diagnostic at 0.400 ps;
    # it is intentionally excluded from Table 8's 0--0.300 ps classical comparison.
    table8 = [{key: row[key] for key in ["trajectory", "time_interval_ps"] + FIELDS8}
              for row in consistency[:4]]
    write_rows(result / "table7.csv", table7)
    write_rows(result / "table8.csv", table8)
    write_rows(result / "retained_vqls_terminal_consistency.csv", consistency[4:])
    labels7 = [
        "Quadratic nonlinear vs. full Lennard--Jones",
        "Continuous $K=2$ Carleman vs. quadratic nonlinear",
        "Backward Euler $K=2$ vs. continuous $K=2$ Carleman",
        "VQLS vs. backward Euler $K=2$", "VQLS vs. full Lennard--Jones",
    ]
    lines7 = [r"% Generated by scripts/build_tables.py; velocities use backward differences.",
              r"\begin{tabular}{llllll}", r"\hline",
              r"Comparison & Error isolated & Maximum $|\Delta q|$ (nm) & RMS $\Delta q$ (nm) & Maximum $|\Delta\widetilde v|$ (nm/ps) & RMS $\Delta\widetilde v$ (nm/ps) \\",
              r"\hline"]
    for label, row in zip(labels7, errors):
        lines7.append(" & ".join([label, row["error_isolated"]] + ["$" + scientific(row[f]) + "$" for f in FIELDS7]) + r" \\")
    lines7.extend([r"\hline", r"\end{tabular}"])
    (result / "table7.tex").write_text("\n".join(lines7) + "\n", encoding="utf-8")
    lines8 = [r"% Generated by scripts/build_tables.py; classical interval 0--0.300 ps.",
              r"\begin{tabular}{lllll}", r"\hline",
              r"Trajectory & Maximum $\eta$ & Terminal $\eta$ & Maximum $\eta^{\mathrm{rel}}$ & Terminal $\eta^{\mathrm{rel}}$ \\",
              r"\hline"]
    for row in consistency[:4]:
        lines8.append(" & ".join([row["trajectory"]] + ["$" + number(row[f]) + "$" for f in FIELDS8]) + r" \\")
    lines8.extend([r"\hline", r"\end{tabular}"])
    (result / "table8.tex").write_text("\n".join(lines8) + "\n", encoding="utf-8")

    # Export the plotted comparisons directly from retained, full-precision data.
    trajectories = read_rows(result / "case3_validation_trajectories.csv")
    figure6 = []
    for row in trajectories:
        figure6.append({
            "frame": round(float(row["time_ps"]) / 0.002), "time_ps": row["time_ps"],
            "atom": int(row["atom_index"]) + 1,
            "vqls_displacement_nm": row["vqls_displacement_nm"],
            "backward_euler_k2_displacement_nm": row["backward_euler_k2_carleman_displacement_nm"],
            "vqls_reconstructed_velocity_backward_nm_per_ps": row["vqls_reconstructed_velocity_backward_nm_per_ps"],
            "backward_euler_k2_reconstructed_velocity_backward_nm_per_ps": row["backward_euler_k2_carleman_reconstructed_velocity_backward_nm_per_ps"],
        })
    write_rows(result / "figure6_series.csv", figure6)
    with np.load(PACKAGE / "inputs/200steps_result_cpu_diagnostics.npz", allow_pickle=False) as data:
        diagnostics = json.loads(str(data["diagnostics"]))[:150]
    figure7 = [{"step": row["step"], "time_ps": row["time"], "vqls_cost": row["vqls_cost"]}
               for row in diagnostics]
    write_rows(result / "figure7_cost_full_precision.csv", figure7)
    costs = np.array([row["vqls_cost"] for row in figure7])
    (result / "figure7_cost_summary.json").write_text(json.dumps({
        "steps": 150, "first_cost": float(costs[0]), "last_cost": float(costs[-1]),
        "mean_cost": float(np.mean(costs)), "max_cost": float(np.max(costs)),
    }, indent=2) + "\n")
    print("Built Tables 7 and 8, Figure 6 series, and full-precision Figure 7 costs.")


if __name__ == "__main__":
    main()
